# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EPATWjX8gsRiMjnpT6A9bJo16UCGwjy5
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

df = pd.read_csv("/content/Customer_Segmentation_Result.csv")
df.head()

#Data Cleaning
df = df.dropna(subset=['CustomerID'])

# The following lines are not applicable as 'Quantity' and 'UnitPrice' columns are not in the current DataFrame.
# df = df[df['Quantity'] > 0]
# df = df[df['UnitPrice'] > 0]

# df['TotalAmount'] = df['Quantity'] * df['UnitPrice']

print(df.shape)

#Data Cleaning
df = df.dropna(subset=['CustomerID'])

# The following lines are not applicable as 'Quantity' and 'UnitPrice' columns are not in the current DataFrame.
# df = df[df['Quantity'] > 0]
# df = df[df['UnitPrice'] > 0]

# df['TotalAmount'] = df['Quantity'] * df['UnitPrice']

print(df.shape)

#Create RFM Features (This dataset already has RFM features, so this step is not needed)
# snapshot_date = df['InvoiceDate'].max() + pd.Timedelta(days=1)

# rfm = df.groupby('CustomerID').agg({
#     'InvoiceDate': lambda x: (snapshot_date - x.max()).days,
#     'InvoiceNo': 'nunique',
#     'TotalAmount': 'sum'
# })

# rfm.columns = ['Recency', 'Frequency', 'Monetary']

# If you intend to use the existing RFM columns for further analysis, you can simply select them:
rfm = df[['CustomerID', 'Recency', 'Frequency', 'Monetary']].copy()
rfm.set_index('CustomerID', inplace=True)

print(rfm.head())

#Feature Scaling
scaler = StandardScaler()

rfm_scaled = scaler.fit_transform(rfm)

#Apply K-Means
kmeans = KMeans(n_clusters=4, random_state=42)

rfm['Cluster'] = kmeans.fit_predict(rfm_scaled)

print(rfm.head())

#Customer Count in Each Cluster
cluster_counts = rfm['Cluster'].value_counts()

print(cluster_counts)

print(rfm['Cluster'].value_counts())

#Cluster Summary
summary = rfm.groupby('Cluster').mean()

print(summary)

#Visualization
plt.figure(figsize=(8,6))

plt.scatter(
    rfm['Frequency'],
    rfm['Monetary'],
    c=rfm['Cluster']
)

plt.xlabel("Frequency")
plt.ylabel("Monetary")
plt.title("Customer Segmentation")

plt.show()

